# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StandingTimerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StandingTimerApp
  pod 'LGButton'
  pod 'R.swift'
  pod 'RxCocoa', '6.0.0-rc.1'
  pod 'RxRelay', '6.0.0-rc.1'
  pod 'RxSwift', '6.0.0-rc.1'

  target 'StandingTimerAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.0.0-rc.1'
    pod 'RxTest', '6.0.0-rc.1'
  end

end

